app/blog/models.py
""" MODELS """
""" FLASK IMPORTS """
from flask_login import UserMixin

"""--------------END--------------"""

""" PYTHON IMPORTS """
from werkzeug.security import generate_password_hash, check_password_hash

"""--------------END--------------"""

""" APP IMPORTS  """
from app import db
from app.core.models import Base

"""--------------END--------------"""

from datetime import datetime
from app.admin.models import Admin


# Sample model
class Post(Base, Admin):
    __tablename__ = 'blog_post'

    user_id = db.Column(db.Integer, db.ForeignKey('auth_user.id'))
    post_title = db.Column(db.String(64))
    content = db.Column(db.Text())
    index_fields = ['Title', 'Created at', 'updated at']
    index_title = "Posts"
    index_message = "Message"
    title = index_title
    model_name = 'Posts'
    model_icon = 'pe-7s-note'
    model_description = "POSTS"
    functions = {'Create post': 'bp_blog.post_create', 'View posts': 'bp_blog.index',
                 'Edit post': 'bp_blog.post_edit', 'Delete post': 'bp_blog.post_delete'}

app/blog/__init__.py
from flask import Blueprint

bp_blog = Blueprint('bp_blog', __name__,)

blueprint_name = "bp_blog"  # The name of the module's blueprint
module_name = "blog"  # The name of the module

# URLS DICTIONARY
# NOTE: CHANGE (model) to your module's model eg. customer_create
blog_urls = {
    'index': '{}.index'.format(blueprint_name),
    'create': '{}.(model)_create'.format(blueprint_name),
    'edit': '{}.(model)_edit'.format(blueprint_name),
    'delete': '{}.(model)_delete'.format(blueprint_name),
}

# TEMPLATES DICTIONARY
# NOTE: CHANGE (model) to your module's model eg. customer_create.html
blog_templates = {
    'index': '{}/blog_index.html'.format(module_name),
    'create': '{}/post_create.html'.format(module_name),
    'edit': '{}/post_edit.html'.format(module_name),
}

from . import routes
from . import models

from .models import Post



class BlogModule:
    module_name = 'blog'
    module_icon = 'fa-rss-square'
    module_link = 'bp_blog.index'
    module_description = 'Blog'
    models = [Post]

app/blog/routes.py
""" ROUTES """

""" FLASK IMPORTS """
from flask import render_template, flash, redirect, url_for, request, jsonify, current_app
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
import base64

"""--------------END--------------"""

""" APP IMPORTS  """
from app.blog import bp_blog
from app import db, context

"""--------------END--------------"""

""" MODULE: AUTH,ADMIN IMPORTS """
from .models import Post

"""--------------END--------------"""

""" URL IMPORTS """
from . import blog_urls

"""--------------END--------------"""

""" TEMPLATES IMPORTS """
from . import blog_templates

"""--------------END--------------"""
from datetime import datetime
from app.admin.routes import admin_index

# This function will change context values depends in view
def change_context(view):
    # VALUES: title, module, active, forms, modal
    context['module'] = 'blog'
    if view == 'index':
        context['title'] = 'Blog'
        context['active'] = 'Posts'
        context['modal'] = True


@bp_blog.route('/')
def index():
    if current_user.is_authenticated:
        posts = Post.query.filter_by(user_id=current_user.id).all()
        print(posts)
        change_context('index')
        return render_template(blog_templates['index'], context=context,posts=posts)
    else:
        posts = Post.query.all()
        change_context('index')
        return render_template(blog_templates['index'], context=context,posts=posts)


@bp_blog.route('/post_create',methods=['GET','POST'])
@login_required
def post_create():
    if request.method == "GET":
        return render_template(blog_templates['create'], context=context)
    elif request.method == "POST":
        title = request.form['title']
        content = request.form['content']
        post = Post()
        post.user_id = int(current_user.id)
        post.post_title = title
        post.content = content
        db.session.add(post)
        db.session.commit()
        flash("Post added successfully!")
        return redirect(url_for(blog_urls['index']))


@bp_blog.route('/post_edit')
@login_required
def post_edit():
    if request.method == "GET":
        fields = [Post.id,Post.post_title,Post.created_at,Post.updated_at]
        return admin_index(Post,fields=fields,url=blog_urls['index'],create_modal=False,
                           view_modal=False,template='blog/post_edit_index.html')


@bp_blog.route('/post_update/<int:post_id>',methods=['GET','POST'])
@login_required
def post_update(post_id):
    post = Post.query.get_or_404(post_id)
    if request.method == "GET":
        return render_template(blog_templates['edit'],post=post,context=context)
    elif request.method == "POST":
        title = request.form['title']
        content = request.form['content']
        post.post_title = title
        post.content = content
        post.updated_at = datetime.utcnow()
        db.session.commit()
        flash("Post update successfully!")
        return redirect(url_for(blog_urls['index']))


@bp_blog.route('/post_destroy/<int:post_id>',methods=['POST'])
@login_required
def post_destroy(post_id):
    try:
        post = Post.query.get_or_404(post_id)
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted successfully!')
        return redirect(url_for(blog_urls['index']))
    except Exception as e:
        context['errors'] = {'Delete error','A problem occured'}
        db.session.rollback()
        return redirect(url_for(blog_urls['index']))


@bp_blog.route('/post_delete',methods=['GET','POST'])
@login_required
def post_delete():
    if request.method == "GET":
        fields = [Post.id, Post.post_title, Post.created_at, Post.updated_at]
        return admin_index(Post, fields=fields, url=blog_urls['index'], create_modal=False,
                           view_modal=False, template='blog/post_delete_index.html')

app/templates/blog/blog_index.html
<!--THIS FILE EXTENDS admin_base.html-->
<!--THIS IS THE DASHBOARD TEMPLATE-->
{% extends "admin/admin_base.html" %}
{% block sidebar %}
{% include 'blog/blog_sidebar.html' %}
{% endblock %}

{% block content %}
<div class="app-main__inner">
    <div class="col-md-12">
        <div class="main-card mb-3 card">
            <div class="card-body">
                <div id="carouselExampleControls1" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <!--                        <div class="carousel-item">-->
                        <!--                            <img class="d-block w-100" src="{{ url_for('static',filename='img/blog/first.png') }}"-->
                        <!--                                 alt="First slide">-->
                        <!--                        </div>-->
                        <div class="carousel-item active">
                            <img style="height:150px;" class="d-block w-100"
                                 src="{{ url_for('static',filename='img/blog1.png') }}"
                                 alt="Second slide">
                        </div>
                        <!--                        <div class="carousel-item">-->
                        <!--                            <img class="d-block w-100" src="{{ url_for('static',filename='img/blog/third.jpg') }}"-->
                        <!--                                 alt="Third slide">-->
                        <!--                        </div>-->
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls1" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls1" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        {% for post in posts %}
        <div class="main-card mb-3 card">
            <div class="card-body">
                <h1 class="card-title">{{ post.post_title|safe }}</h1>
                <div class="collapse" id="collapseID{{ post.id }}">
                {{ post.content|safe }}
                </div>
            </div>
            <div class="card-footer">
                <button type="button" data-toggle="collapse" href="#collapseID{{ post.id }}"
                        class="mb-2 mr-2 border-0 btn-transition btn btn-outline-warning collapsed" aria-expanded="false">View post
                </button>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block toast %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div id="toast-container" class="toast-top-center">
    {% for message in messages %}
    <div class="toast toast-success" aria-live="polite" style="">
        <div class="toast-progress" style="width: 0%;"></div>
        <button type="button" class="toast-close-button" role="button" onclick="close_toast()">×</button>
        <div class="toast-title">Saved!</div>
        <div class="toast-message">{{ message }}</div>
    </div>
</div>

{% endfor %}
{% endif %}
{% endwith %}

{% if context['errors'] %}
<div id="toast-container" class="toast-top-center">
    {% for key,error in context['errors'].items() %}
    <div class="toast toast-error" aria-live="polite" style="">
        <div class="toast-progress" style="width: 0%;"></div>
        <button type="button" class="toast-close-button" role="button" onclick="close_toast()">×</button>
        <div class="toast-title">Error!</div>
        <div class="toast-message">{{ key, error }}</div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

app/templates/blog/blog_sidebar.html
{% extends "admin/admin_sidebar.html" %}
{% block first_sidebar_navigation %}
<li class="app-sidebar__heading">System Models</li>
{% for key,value in context['system_modules'].items() %}
{% if key == context['module'] %}
{% for model_name,val in value['models'].items() %}
<li>
    <a href="#" class="{% if context['active']==model_name %} mm-active {% endif %}">
        <i class="metismenu-icon {{ val['icon'] }} icon-gradient bg-premium-dark" aria-hidden="true"></i>
        {{ model_name }}
        <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
    </a>
    <ul>
        {% for function,link in val['functions'].items() %}
        <li>
            <a href="{{ url_for(link) }}">
                <i class="metismenu-icon">
                </i>{{ function }}
            </a>
        </li>
        {% endfor %}
    </ul>
</li>
{% endfor %}
{% endif %}
{% endfor %}
{% endblock %}

{% block second_sidebar_navigation %}
<li class="app-sidebar__heading">Posts</li>
<ul>
    {% for post in posts %}
    <li>
        <a href="#">
            <i class="metismenu-icon">
            </i>{{ post.post_title }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/blog/post_create.html
{% extends "blog/blog_index.html" %}
{% block content %}
<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-graph text-success"> </i>
                </div>
                <div>
                    Create Post
                    <div class="page-title-subheading">

                    </div>
                </div>
            </div>
        </div>
    </div>
    <form action="{{ url_for('bp_blog.post_create') }}" id="post_create_form"
          class="needs-validation" method="POST" novalidate>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="main-card mb-3 card">
            <div class="card-body">
                <div class="form-row">
                    <div class="col-md-6 mb-3">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" name="title" placeholder="Post title"
                               required>
                        <div class="valid-feedback">
                            {{ current_user.fname }} you're so good!
                        </div>
                        <div class="invalid-feedback">
                            {{ current_user.fname }} add your title!
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-12 mb-3">
                        <label for="content">Content</label>
                        <textarea name="content" id="content" class="form-control"
                        cols="30" rows="5"></textarea>
                    </div>
                </div>
                <script>
            // Example starter JavaScript for disabling form submissions if there are invalid fields
            (function() {
            'use strict';
            window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
            if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
            }
            form.classList.add('was-validated');
            }, false);
            });
            }, false);
            })();
                </script>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block inner_footer %}
<div class="app-footer-right">
    <button type="button" class="btn btn-secondary">Cancel</button>
    <button form="post_create_form" type="submit" class="btn btn-primary">Save</button>
</div>
{% endblock %}

{% block scripts %}
<script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>
{% endblock %}

app/templates/blog/post_delete_index.html
{% extends "blog/blog_index.html" %}
{% block content %}
<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-drawer icon-gradient bg-happy-itmeo"> </i>
                </div>
                <div>
                    {{ index_title }}
                    <div class="page-title-subheading">
                        {{ index_message }}
                    </div>
                </div>
            </div>
            {% block actions %}
            {% if action %}
            {% include action %}
            {% endif %}
            {% endblock %}
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <table id="index_table" class="mb-0 table table-hover table-bordered table-striped">
                        <thead>
                        <tr>
                            {% for field in table_fields %}
                            <th>{{ field.upper() }}</th>
                            {% endfor %}
                            <th>DELETE</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for model in models %}
                        {% if view_modal %}
                        <tr id="{{ model[0] }}" onclick="row_click(this, '{{context['active']}}')" data-toggle="modal"
                            data-target="#viewModal">
                            <param id="{{ model[0] }}" name="{{ url_for(edit_url,oid=model[0]) }}">
                            {% else %}
                        <tr>
                            {% endif %}

                            {% for values in model %}
                            {% if loop.index > 1 %}
                            <td>{{ values }}</td>

                            {% endif %}
                            {% endfor %}
                            <td>
                                <form action="{{url_for('bp_blog.post_destroy',post_id=model[0])}}"
                                      method="POST">
                                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                    <button type="submit" class="mb-2 mr-2 btn-transition btn btn-outline-danger">This
                                        post
                                    </button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block inner_footer %}
<div class="app-footer-left">
    <nav class="" aria-label="Page navigation example">
        <ul class="pagination">
            {% if prev_url %}
            <li class="page-item">
                <a href="{{ prev_url }}" class="page-link" aria-label="Previous">
                    <span aria-hidden="true">Previous</span>
                    <span class="sr-only">Previous</span></a>
            </li>
            {% endif %}

            {% if next_url %}
            <li class="page-item">
                <a href="{{ next_url }}" class="page-link" aria-label="Next">
                    <span aria-hidden="true">Next</span>
                    <span class="sr-only">Next</span></a></li>
        </ul>
        {% endif %}
    </nav>
</div>
{% endblock %}

{% block scripts %}
<script>
    function add_delete_column(){
        var tr = document.getElementById('index_table').tHead.children[0];
        th = document.createElement('th');
        th.innerHTML = "Delete";
        tr.appendChild(th);
        var new_cell = '\<div class="custom-checkbox custom-control"><input type="checkbox" id="" class="custom-control-input"><label class="custom-control-label" for=""></label></div>';

        var table = document.getElementById("index_table");

        for (var r = 1; r < table.rows.length; r++) {
            table.rows[r].cells[5].insertAdjacentHTML('beforeend', new_cell);
        }
    }








</script>
{% endblock %}

{% block toast %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div id="toast-container" class="toast-top-center">
    {% for message in messages %}
    <div class="toast toast-success" aria-live="polite" style="">
        <div class="toast-progress" style="width: 0%;"></div>
        <button type="button" class="toast-close-button" role="button" onclick="close_toast()">×</button>
        <div class="toast-title">Saved!</div>
        <div class="toast-message">{{ message }}</div>
    </div>
</div>

{% endfor %}
{% endif %}
{% endwith %}

{% if context['errors'] %}
<div id="toast-container" class="toast-top-center">
    {% for key,error in context['errors'].items() %}
    <div class="toast toast-error" aria-live="polite" style="">
        <div class="toast-progress" style="width: 0%;"></div>
        <button type="button" class="toast-close-button" role="button" onclick="close_toast()">×</button>
        <div class="toast-title">Error!</div>
        <div class="toast-message">{{ key, error }}</div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

app/templates/blog/post_edit.html
{% extends "blog/blog_index.html" %}
{% block content %}
<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-graph text-success"> </i>
                </div>
                <div>
                    Edit Post
                    <div class="page-title-subheading">

                    </div>
                </div>
            </div>
        </div>
    </div>
    <form action="{{ url_for('bp_blog.post_update',post_id=post.id) }}" id="post_edit_form"
          class="needs-validation" method="POST" novalidate>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="main-card mb-3 card">
            <div class="card-body">
                <div class="form-row">
                    <div class="col-md-6 mb-3">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" name="title" placeholder="Post title"
                               required value="{{ post.post_title }}">
                        <div class="valid-feedback">
                            {{ current_user.fname }} you're so good!
                        </div>
                        <div class="invalid-feedback">
                            {{ current_user.fname }} add your title!
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-12 mb-3">
                        <label for="content">Content</label>
                        <textarea name="content" id="content" class="form-control"
                        cols="30" rows="5">{{ post.content }}</textarea>
                    </div>
                </div>
                <script>
            // Example starter JavaScript for disabling form submissions if there are invalid fields
            (function() {
            'use strict';
            window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
            if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
            }
            form.classList.add('was-validated');
            }, false);
            });
            }, false);
            })();
                </script>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block inner_footer %}
<div class="app-footer-right">
    <button type="button" class="btn btn-secondary">Cancel</button>
    <button form="post_edit_form" type="submit" class="btn btn-primary">Save</button>
</div>
{% endblock %}

{% block scripts %}
<script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>
{% endblock %}

app/templates/blog/post_edit_index.html
{% extends "blog/blog_index.html" %}
{% block content %}
<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-drawer icon-gradient bg-happy-itmeo"> </i>
                </div>
                <div>
                    {{ index_title }}
                    <div class="page-title-subheading">
                        {{ index_message }}
                    </div>
                </div>
            </div>
            {% block actions %}
            {% if action %}
            {% include action %}
            {% endif %}
            {% endblock %}
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <table id="index_table" class="mb-0 table table-hover table-bordered table-striped">
                        <thead>
                        <tr>
                            {% for field in table_fields %}
                            <th>{{ field.upper() }}</th>
                            {% endfor %}
                            <th>EDIT</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for model in models %}
                        {% if view_modal %}
                        <tr id="{{ model[0] }}" onclick="row_click(this, '{{context['active']}}')" data-toggle="modal"
                            data-target="#viewModal">
                            <param id="{{ model[0] }}" name="{{ url_for(edit_url,oid=model[0]) }}">
                            {% else %}
                        <tr>
                            {% endif %}

                            {% for values in model %}
                            {% if loop.index > 1 %}
                            <td>{{ values }}</td>

                            {% endif %}
                            {% endfor %}
                            <td>
                                <a href="{{ url_for('bp_blog.post_update',post_id=model[0]) }}" class="mb-2 mr-2 btn-transition btn btn-outline-success">This
                                    post
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block inner_footer %}
<div class="app-footer-left">
    <nav class="" aria-label="Page navigation example">
        <ul class="pagination">
            {% if prev_url %}
            <li class="page-item">
                <a href="{{ prev_url }}" class="page-link" aria-label="Previous">
                    <span aria-hidden="true">Previous</span>
                    <span class="sr-only">Previous</span></a>
            </li>
            {% endif %}

            {% if next_url %}
            <li class="page-item">
                <a href="{{ next_url }}" class="page-link" aria-label="Next">
                    <span aria-hidden="true">Next</span>
                    <span class="sr-only">Next</span></a></li>
        </ul>
        {% endif %}
    </nav>
</div>
{% endblock %}

{% block scripts %}
<script>
    function add_delete_column(){
        var tr = document.getElementById('index_table').tHead.children[0];
        th = document.createElement('th');
        th.innerHTML = "Delete";
        tr.appendChild(th);
        var new_cell = '\<div class="custom-checkbox custom-control"><input type="checkbox" id="" class="custom-control-input"><label class="custom-control-label" for=""></label></div>';

        var table = document.getElementById("index_table");

        for (var r = 1; r < table.rows.length; r++) {
            table.rows[r].cells[5].insertAdjacentHTML('beforeend', new_cell);
        }
    }






</script>
{% endblock %}

{% block toast %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div id="toast-container" class="toast-top-center">
    {% for message in messages %}
    <div class="toast toast-success" aria-live="polite" style="">
        <div class="toast-progress" style="width: 0%;"></div>
        <button type="button" class="toast-close-button" role="button" onclick="close_toast()">×</button>
        <div class="toast-title">Saved!</div>
        <div class="toast-message">{{ message }}</div>
    </div>
</div>

{% endfor %}
{% endif %}
{% endwith %}

{% if context['errors'] %}
<div id="toast-container" class="toast-top-center">
    {% for key,error in context['errors'].items() %}
    <div class="toast toast-error" aria-live="polite" style="">
        <div class="toast-progress" style="width: 0%;"></div>
        <button type="button" class="toast-close-button" role="button" onclick="close_toast()">×</button>
        <div class="toast-title">Error!</div>
        <div class="toast-message">{{ key, error }}</div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}